### ISSUE TITLE
Unable to add versions

### ISSUE THREAD

**Issue by Zooce** [gcuisinier/jenv#106]
I just installed `jenv` with Homebrew and updated `~/.bash_profile` with:
```
if which jenv > /dev/null; then eval "$(jenv init -)"; fi
export JENV_ROOT="/usr/local/opt/jenv"
```
Now this happens:
```
$ jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/
ln: /usr/local/opt/jenv/versions/oracle64-1.8.0.51: No such file or directory
```

**Comment by gcuisinier** [comment]
Do you have close/reopen terminal before adding jdk ?
If not, the bash_profile has not been read, so the initialisation is not yet done

**Comment by Zooce** [comment]
Yea, I always close and reopen the terminal when changing ~/.bash_profile.

**Comment by gcuisinier** [comment]
Ok.
Could you provide me output of "jenv doctor" ?

**Comment by Zooce** [comment]
$ jenv doctor
[OK]	No JAVA_HOME set
[ERROR]	Java binary in path is not in the jenv shims.
[ERROR]	Please check your path, or try using /path/to/java/home is not a valid path to java installation.
	PATH : /usr/local/Cellar/jenv/0.4.3/libexec/libexec:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/Users/zooce/.jenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[OK]	Jenv is correctly loaded

**Comment by gcuisinier** [comment]
Could you change the order of 
```if which jenv > /dev/null; then eval "$(jenv init -)"; fi
export JENV_ROOT="/usr/local/opt/jenv"```

to

```
export JENV_ROOT="/usr/local/opt/jenv"
if which jenv > /dev/null; then eval "$(jenv init -)"; fi
```

And try again ?

**Comment by Zooce** [comment]
That worked! Thanks @gcuisinier, I appreciate it :)

**Comment by ernestkamara** [comment]
Thank @gcuisinier! You save me some hours.

**Comment by GeoffreyBooth** [comment]
This worked for me too. It should really be added to https://github.com/gcuisinier/jenv/wiki/Trouble-Shooting

**Comment by atljoseph** [comment]
i did this and still not working
