### ISSUE TITLE
jenv golbal cannot change jdk version 

### ISSUE THREAD

**Issue by CaiHuan** [gcuisinier/jenv#108]
jenv golbal cannot change jdk version but this script can(in mac)
function setjdk() {
  if [ $# -ne 0 ]; then
   removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'
   if [ -n "${JAVA_HOME+x}" ]; then
    removeFromPath $JAVA_HOME
   fi
   export JAVA_HOME=`/usr/libexec/java_home -v $@`
   export PATH=$JAVA_HOME/bin:$PATH
  fi
 }
 function removeFromPath() {
  export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
 }
setjdk 1.7

**Comment by CaiHuan** [comment]
the http://jenv.io/  also can change jdk version

**Comment by smithtrenton** [comment]
I think this is related, but I have to do `source ~/.zshrc` after using jenv global in order for it to fully change my jdk version.

**Comment by mikehagerty** [comment]
Same thing: jenv global does not change jdk version on mac os x (10.10.5)
Does anyone know why ? Also, jenv doesn't set JAVA_HOME, which seems
kind of important (?)

**Comment by gcuisinier** [comment]
try ```jenv enable-plugin export```
