### ISSUE TITLE
jenv fails to set JAVA_HOME

### ISSUE THREAD

**Issue by mcandre** [gcuisinier/jenv#112]
jenv appears to fail to set JAVA_HOME, e.g. when using jenv with java 1.7. Am I doing something wrong?

https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/jenv.sh

**Comment by dkowis** [comment]
I just ran into this problem as well, but I'm not sure what I'm doing wrong either.

**Comment by jangalinski** [comment]
+1

**Comment by dkowis** [comment]
Using the export plugin: https://github.com/gcuisinier/jenv#plugins sets the java home properly. Duplicate of #123
