### ISSUE TITLE
Why jenv is creating multiple similar versions?

### ISSUE THREAD

**Issue by achittin** [gcuisinier/jenv#121]
When I am running jenv versions its displaying as 1.6, 1.6.0.51 and oracle64-1.6.0.51. Aren't they all the same?

**Comment by gcuisinier** [comment]
That allow you to simply choose major JDK (  1.6 ) but also to choose a very specific JDK when needed.
Ex : Some time, choosing a very specific JDK is needed to reproduce a bug (only on the version xxx, or only on the version xxx of the ibm provider, .. )
