### ISSUE TITLE
How does jenv work with fish shell?

### ISSUE THREAD

**Issue by haifzhan** [gcuisinier/jenv#126]
I am using jenv with fish shell. I followed the jenv instructions on Github, unfortunately it seems not working with fish shell.

Please help, it does work even I invoke 'jenv global oracel64-1.7.0.79', the version is still java8.

$> jenv versions                                                                                                                                                                               Mon  7 Dec 2015 14:22:00 MST
  system
  1.7
* 1.7.0.79 (set by /Users/hzhang/work/battleground/.java-version)
  1.8
  1.8.0.60
  oracle64-1.7.0.79
  oracle64-1.8.0.60
$>  jenv doctor                                                                                                                                                                                 Mon  7 Dec 2015 14:22:07 MST
[OK]	No JAVA_HOME set
[ERROR]	Java binary in path is not in the jenv shims.
[ERROR]	Please check your path, or try using /path/to/java/home is not a valid path to java installation.
	PATH : /Users/haifzhan/.jenv/libexec:/Users/hzhang/.jenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
[ERROR]	Jenv is not loaded in your fish
[ERROR]	To fix : 	cat eval "$(jenv init -)" >> your profile

**Comment by stirp** [comment]
Did you tried to put the script file jenv.fish(https://github.com/gcuisinier/jenv/blob/master/fish/jenv.fish) into ~/.oh-my-fish/functions/ if you are using oh-my-fish?
If your fish has function export (executing "functions | grep export" that get "export"), you could simply add export JENV_LOADED=1 into jenv.fish.
If your fish doesn't have the function export, put export.fish (https://github.com/gcuisinier/jenv/blob/master/fish/export.fish) into your functions folder, then add export JENV_LOADED=1 into your jenv.fish.

**Comment by haifzhan** [comment]
@stirp  Thanks. I figured out there's a typo for my function folder name. jenv works after I correct the typo.

**Comment by Puneet-Patwari** [comment]
@stirp Thanks. works like a charm. Wasted an hour trying to solve it.
