### ISSUE TITLE
unset JDK_HOME as well as JAVA_HOME

### ISSUE THREAD

**Issue by fommil** [gcuisinier/jenv#128]
`JDK_HOME` is used by many developer tools to distiguish from the JRE at `JAVA_HOME`. It would be great if you either unset both, or set both consistently.

@dwijnand

**Comment by hanxue** [comment]
`jenv` does not set the `JDK_HOME` environment variable. You will not the existing of `JDK_HOME` in `jenv`'s source code [Search JDK_HOME](https://github.com/gcuisinier/jenv/search?utf8=%E2%9C%93&q=jdk_home&type=Code)

Perhaps `JDK_HOME` is set in a startup / shell config file or an application?

**Comment by fommil** [comment]
Yes, that's the point. Enter set it or unset it but he not leave it untouched.

**Comment by dwijnand** [comment]
@gcuisinier I see you've added managing `JDK_HOME` to `export_jenv_hook`, which is great.

But I also think it should be managed (ie. unset) in `jenv-init` (and perhaps also in `jenv-doctor`). WDYT?

**Comment by fommil** [comment]
I just tried out jenv and although a `local` `.java-version` is unsetting the `JAVA_HOME` it is still not unsetting a `JDK_HOME`
