### ISSUE TITLE
Setting JAVA_HOME, using export plugin?

### ISSUE THREAD

**Issue by ianjohnspain** [gcuisinier/jenv#137]
Hi,

Found a few people saying they couldn't get the JAVA_HOME to set correctly and the advice was to use the export plugin but i can find no info on this. Has it been removed ? Or maybe I am just not looking correctly.

here is an example 

      https://github.com/gcuisinier/jenv/issues/112

It states to check and use the export plugin here but I can't find any reference to the export plugin here 

      https://github.com/gcuisinier/jenv#plugins

Can anyone help or confirm what I am doing wrong ?

Thanks

**Comment by gcuisinier** [comment]
Export plugin is well present, but indeed, not documented !
I will fix it asap !

Thanks

**Comment by binarysqueeze** [comment]
Thanks @gcuisinier

**Comment by ianjohnspain** [comment]
Just tested this now as I saw the instructions were updated. Works as expected! Thanks
