### ISSUE TITLE
Gradle plugin should work with gradlew as well

### ISSUE THREAD

**Issue by jonatan-ivanov** [gcuisinier/jenv#140]
Gradle plugin works fine but unfortunately it does not work with gradlew: https://docs.gradle.org/current/userguide/gradle_wrapper.html

```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_71.jdk/Contents/Home

$ jenv local
1.7

$ gradle --version
------------------------------------------------------------
Gradle 2.11
------------------------------------------------------------
[...]
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
[...]

$ gradlew --version 
------------------------------------------------------------
Gradle 2.11
------------------------------------------------------------
[...]
JVM:          1.8.0_71 (Oracle Corporation 25.71-b15)
[...]
```

However enabling export plugin solves the issue.

**Comment by gcuisinier** [comment]
The main problem is that gradlew is mainly used with `./gradlew`.
And so, the $PATH is not used to discover "gradlew" command.

jenv is modifying $PATH to handle interception.

**Comment by dobermai** [comment]
Shouldn't this work with the export plugin? Seems ./gradlew uses JAVA_HOME.

**Comment by gcuisinier** [comment]
If gradlew use JAVA_HOME, yes that should work :-)

**Comment by jonatan-ivanov** [comment]
Have you checked the last line of the issue? :)

**Comment by djangofan** [comment]
I am assuming that when use the gradle command from anywhere on your system, it will generate a directory cache at ~/.gradle  .   Now, on the other hand, if you run 'gradle wrapper' from any other directory outside of ~/   , it will create a secondary .gradle folder cache in that location, which is used by gradlew .  @jonatan-ivanov That might explain the difference.

**Comment by jonatan-ivanov** [comment]
@djangofan
I don't see how can this explain anything. :)
Don't assume that, it's not true. :) Both `~/.gradle` (home) and `./.gradle` (on your project root) directories will always be created, it does not matter if you called `gradle` or `./gradlew`. The contents of the directories are different as well as their purpose.

**Comment by jonatan-ivanov** [comment]
Close: enabling export plugin solves the issue.
