### ISSUE TITLE
allow force override of add_alias_check

### ISSUE THREAD

**Issue by fommil** [gcuisinier/jenv#158]
when running in automated builds, the check in `add_alias_check` is difficult to deal with (workaround is to anticipate collisions and jenv-remove them) it would be nicer to be able to allow a way to default to `y` without a `read`

**Comment by antonagestam** [comment]
So, a pretty ugly workaround for this is to do `yes | jenv add <path>`, but it works. Would be nice with a `-y` or `--assume-yes` or `--no-input` though.
