### ISSUE TITLE
JAVA_HOME variable was erased after <eval "$(jenv init -)">

### ISSUE THREAD

**Issue by chamhaw** [gcuisinier/jenv#197]
**OS: Mac OS 10.13.4 (17E199)**

**jenv version: 0.4.4**

I tested with JDK 1.8&10
- eval "$(jenv init -)" before exporting JAVA_HOME
```sh
eval "$(jenv init -)"
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```

```bash
>$ echo $JAVA_HOME
>$ /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
```

- eval "$(jenv init -)" after exporting JAVA_HOME
```sh
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
eval "$(jenv init -)"
```

```sh
>$ echo $JAVA_HOME
>$ <blank> #JAVA_HOME was erased!
```

**Comment by chamhaw** [comment]
Some softwares which need JAVA_HOME don't work such as apache-maven.

**Comment by gcuisinier** [comment]
That is the right behavior.

You can use specific jenv plug-in for exporting Java home for specific
tools like maven.

Or use the export plug-in to export JAVA_HOME according the JDK use with
jenv

**Comment by chamhaw** [comment]
@gcuisinier I'm sorry to read the official website only. It works well now thanks to README.md.

**Comment by gcuisinier** [comment]
No problem.

I should probably add this on the website explicitly
