### ISSUE TITLE
SHA Mismatch error 

### ISSUE THREAD

**Issue by bshakil** [gcuisinier/jenv#32]
brew install https://raw.github.com/hikage/homebrew/master/Library/Formula/jenv.rb
######################################################################## 100.0%
==> Downloading https://github.com/hikage/jenv/tarball/0.1.1
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: fc672332d8f9013c6806d04d745b11af74f94808
Actual: 3bc0b09f0f7b53e865cdbb4fda6e715cfa0ada56
Archive: /Library/Caches/Homebrew/jenv-0.1.1.tgz
(To retry an incomplete download, remove the file above.)
Burhans-MacBook-Pro:Applications administrator$

**Comment by gcuisinier** [comment]
No more needed, jenv is on official homebrew
