### ISSUE TITLE
Jenv not setting JAVA_HOME

### ISSUE THREAD

**Issue by kellizer** [gcuisinier/jenv#44]
Did I miss something; i'm trying to reset my JAVA_HOME with jenv and have tried all the command and it seems it is updating the values but not the JAVA_HOME? 

Any reason this should be happening?

Thanks,

Ian.

```shell
Ians-MacBook-Pro:~ ian$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
Ians-MacBook-Pro:~ ian$ jenv local oracle64-1.7.0.45
Ians-MacBook-Pro:~ ian$ jenv global oracle64-1.7.0.45 
Ians-MacBook-Pro:~ ian$ jenv shell
shell          shell-options  
Ians-MacBook-Pro:~ ian$ jenv shell oracle64-1.7.0.45 
Ians-MacBook-Pro:~ ian$ jenv version
oracle64-1.7.0.45 (set by JENV_VERSION environment variable)
Ians-MacBook-Pro:~ ian$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
Ians-MacBook-Pro:~ ian$ jenv versions
  system
  oracle64-1.6.0.65
* oracle64-1.7.0.45 (set by JENV_VERSION environment variable)
  oracle64-1.8.0-ea
Ians-MacBook-Pro:~ ian$ echo $JENV_VERSION
oracle64-1.7.0.45
Ians-MacBook-Pro:~ ian$ cat .java-version
oracle64-1.7.0.45
Ians-MacBook-Pro:~ ian$ ```

**Comment by babu-rajendran** [comment]
I have tried "jenv enable-plugin export". But still JAVA_HOME environment is not getting set for me.

**Comment by ddossot** [comment]
@babu-rajendran Did you restart your shell (or sourced `.bashrc`) after activating the plug-in?

**Comment by babu-rajendran** [comment]
Yes. I have restarted my shell and this is what I have in my .bashrc

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

**Comment by ddossot** [comment]
Very odd.

Do you have a local `.java-version` file or a global version defined when you run `echo $JAVA_HOME`?

What version of jenv do you run BTW?

**Comment by babu-rajendran** [comment]
I do not have a local .java-version file. I am setting the java version globally. You can take a look at this screenshot.
http://screencast.com/t/fsAgYoxeo4

The version of jenv I am running is 0.4.2

**Comment by ddossot** [comment]
Thanks for the extra info. Alas, I can't see what's going here. Hopefully, someone else will. @gcuisinier maybe?

**Comment by gcuisinier** [comment]
Strange indeed.
You are running under bash ?

Could you give me the output of :

```
jenv doctor
echo $PROMPT_COMMAND
```

**Comment by babu-rajendran** [comment]
Yes! I am running under bash.
Here is the output of the commands you gave:
```
[brajendran@L-C02FF6N5DF91:~]$ jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
[brajendran@L-C02FF6N5DF91:~]$ echo $PROMPT_COMMAND

[brajendran@L-C02FF6N5DF91:~]$
```

**Comment by gcuisinier** [comment]
Ok so the export plugin is not well activated ...

Could you create a "test.sh" script with that content : 

```
#!/bin/bash
echo $JENV_HOOK_PATH
echo $SHELL
```

and do ```jenv exec ./test.sh````

**Comment by babu-rajendran** [comment]
I have done that.

```
[brajendran@L-C02FF6N5DF91:~]$ cat test.sh
#!/bin/bash
echo $JENV_HOOK_PATH
echo $SHELL

[brajendran@L-C02FF6N5DF91:~]$ jenv exec ./test.sh
:/Users/brajendran/.jenv/plugins/export/etc/jenv.d
/usr/local/bin/shell
[brajendran@L-C02FF6N5DF91:~]$

```

**Comment by gcuisinier** [comment]
ok, I found the bug.
I expect the shell to be "bash", "zsh" or "fish ..

Here it's "/usr/lcal/bin/shell" .. and so that's don't work correctly.

To fix, modify you .bash_profiles from :
```
eval "$(jenv init -)
```

to
```
eval "$(jenv init - bash)
```

**Comment by babu-rajendran** [comment]
Thank you so much! It is working now and JAVA_HOME is set correctly.

**Comment by zinking** [comment]
@gcuisinier  can we add `jenv exec /your/command/here`  this line to the README file? 
I forget it from time to time and it takes effort to search this page.

**Comment by dattatre263** [comment]
Sorry but I have the same problem.  Eventhough I enabled maven I still do not see maven referring Jenv selected JVM.

$ jenv --version
jenv 0.4.0
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 08:22:22-0700)
Maven home: /usr/local/apache-maven/apache-maven-3.1.1
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
$ jenv versions
  system
  1.6
  1.6.0.65
  1.8
  1.8.0.31
  oracle64-1.6.0.65
* oracle64-1.8.0.31 (set by /Users/CHI\dparupud/.jenv/version)
$ jenv enable-plugin maven
maven plugin activated
$ mvn -version 
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 08:22:22-0700)
Maven home: /usr/local/apache-maven/apache-maven-3.1.1
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

**Comment by zinking** [comment]
@dattatre263  my solution is as to execute the command after `jenv exec *cmd*`

**Comment by dattatre263** [comment]
Are you suggesting I do the following 

$ jenv exec mvn clean install ?

because when I say the following I get the correct java version.

$ jenv exec mvn -version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 08:22:22-0700)
Maven home: /usr/local/apache-maven/apache-maven-3.1.1
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

**Comment by gcuisinier** [comment]
Could you provide output of 

```jenv doctor```

```command -v mvn```

**Comment by dattatre263** [comment]
$ jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
$ command -v mvn
/usr/local/apache-maven/apache-maven-3.1.1/bin/mvn

**Comment by gcuisinier** [comment]
Ok.. It seems that the maven plugin is not correctly loaded.
Could you try again :
```jenv enable-plugin maven
command -v mvn```

**Comment by dattatre263** [comment]
$ jenv enable-plugin maven
maven plugin already enabled
$ command -v mvn
/usr/local/apache-maven/apache-maven-3.1.1/bin/mvn
$

**Comment by gcuisinier** [comment]
Could you provide output of 
```echo $PATH```

**Comment by dattatre263** [comment]
$ echo $PATH
/Users/CHI\dparupud/.jenv/shims:/Users/CHI\dparupud/.jenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/apache-maven/apache-maven-3.1.1/bin

**Comment by gcuisinier** [comment]
Mmm .. there is a bug somewhere.
Can you list 

``ls /Users/CHI\dparupud/.jenv/shims```

I presume that mvn wrapper shim is not correctly created

**Comment by dattatre263** [comment]
@gcuisinier, thanks for all your help.
I thought maybe because of CHI\ ( backslash) was causing all this issue. I recreated my account on my mac.

Now my ~ ( home) points to
/Users/dparupud.

however I don't find .jenv folder in my home directory now. I did a brew uninstall and install again still with no luck. I think this is not an issue anymore but a problem specific to mine.  I apologize for the confusion. 

What is the best way to uninstall jenv completely ? Apologies again.

**Comment by dattatre263** [comment]
I think my problem is solved.

dparupudi-mac:~ dparupud$ jenv global oracle64-1.8.0.31
dparupudi-mac:~ dparupud$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
dparupudi-mac:~ dparupud$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 08:22:22-0700)
Maven home: /usr/local/apache-maven/apache-maven-3.1.1
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
dparupudi-mac:~ dparupud$ jenv global oracle64-1.6.0.65
dparupudi-mac:~ dparupud$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 08:22:22-0700)
Maven home: /usr/local/apache-maven/apache-maven-3.1.1
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

**Comment by ihliedaily** [comment]
First of all: gcuisinier, you did a great job!

But unfortunately i also have a problem. I am using Fish and Jenv (first tried via brew, then installed manually) and have the following outputs:

`↪  jenv doctor                                                                                                                                                                                                                                      
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[ERROR]	Jenv is not loaded in your fish
[ERROR]	To fix : 	cat eval "$(jenv init -)" >> your profile` 

`↪  echo $PATH                                                                                                                                                                                                                                       
/Users/swn/.jenv/shims /Users/swn/.jenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin`

`↪  jenv shell                                                                                                                                                                                                                                       
jenv: no such command `shell'`

`↪  jenv enable-plugin maven                                                                                                                                                                                                                         
jenv: no such command 'enable-plugin'`

`↪  ls /Users/swn/.jenv/shims                                                                                                                                                                                                                        
appletviewer   idlj           java           javafxpackager javaws         jdb            jmap           jrunscript     jstat          keytool        pack200        rmid           serialver      unpack200      xjc
apt            jar            javac          javah          jcmd           jhat           jmc            jsadebugd      jstatd         native2ascii   policytool     rmiregistry    servertool     wsgen
extcheck       jarsigner      javadoc        javap          jconsole       jinfo          jps            jstack         jvisualvm      orbd           rmic           schemagen      tnameserv      wsimport
`

`↪  cat ~/.config/fish/config.fish                                                                                                                                                                                                                   Mo 30 Mär 2015 19:13:22 CEST
# Path to your oh-my-fish.
set fish_path $HOME/.oh-my-fish

# Theme
set fish_theme jacaetevha

# All built-in plugins can be found at ~/.oh-my-fish/plugins/
# Custom plugins may be added to ~/.oh-my-fish/custom/plugins/
# Enable plugins by adding their name separated by a space to the line below.
set fish_plugins theme

# Path to your custom folder (default path is ~/.oh-my-fish/custom)
#set fish_custom $HOME/dotfiles/oh-my-fish

# Load oh-my-fish configuration.
. $fish_path/oh-my-fish.fish

set fish_plugins git-flow

set PATH $HOME/.jenv/bin $PATH
set PATH /Users/swn/.jenv/shims $PATH

jenv rehash 2>/dev/null

set JENV_LOADED 1
set JAVA_HOME
`

and last:

`↪  jenv global 1.6 
↪  java -version                                                                                                                                                                                                                                    
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)`

What am i missing? (it's the same with or without oh-my-fish)

**Comment by solidjb** [comment]
What I did is a little bit of a hack, but I think that it would remove the need for all of the plugins.

Inside of the .jenv directory, I created a fake-java-home/bin with a symlink to the shims directory.  Then in my bash, I pointed JAVA_HOME to the .jenv/fake-java-home directory.  This means that any program trying to use java, will be redirected to the shim automatically.

<pre>
bakerj1-mbpdu:.jenv bakerj$ ls -al
total 32
drwxr-xr-x  21 bakerj  OCLC\Domain Users   714 Apr 13 14:12 .
drwxr-xr-x+ 56 bakerj  OCLC\Domain Users  1904 Apr 13 14:44 ..
drwxr-xr-x  13 bakerj  OCLC\Domain Users   442 Apr  9 16:15 .git
-rw-r--r--   1 bakerj  OCLC\Domain Users     0 Apr  9 16:20 1.7.0.45.time
-rw-r--r--   1 bakerj  OCLC\Domain Users     0 Apr  9 16:20 1.7.time
-rw-r--r--   1 bakerj  OCLC\Domain Users     0 Apr  9 16:20 1.8.0.05.time
-rw-r--r--   1 bakerj  OCLC\Domain Users     0 Apr  9 16:20 1.8.time
-rw-r--r--   1 bakerj  OCLC\Domain Users  1060 Apr  9 16:15 LICENSE
-rw-r--r--   1 bakerj  OCLC\Domain Users  6385 Apr  9 16:15 README.md
drwxr-xr-x  13 bakerj  OCLC\Domain Users   442 Apr  9 16:15 available-plugins
drwxr-xr-x   3 bakerj  OCLC\Domain Users   102 Apr  9 16:15 bin
drwxr-xr-x   4 bakerj  OCLC\Domain Users   136 Apr  9 16:15 completions
drwxr-xr-x   3 bakerj  OCLC\Domain Users   102 Apr 13 14:13 fake-java-home
drwxr-xr-x   4 bakerj  OCLC\Domain Users   136 Apr  9 16:15 fish
drwxr-xr-x  44 bakerj  OCLC\Domain Users  1496 Apr  9 16:15 libexec
-rw-r--r--   1 bakerj  OCLC\Domain Users     0 Apr  9 16:20 oracle64-1.7.0.45.time
-rw-r--r--   1 bakerj  OCLC\Domain Users     0 Apr  9 16:20 oracle64-1.8.0.05.time
drwxr-xr-x   4 bakerj  OCLC\Domain Users   136 Apr 13 14:42 plugins
drwxr-xr-x  51 bakerj  OCLC\Domain Users  1734 Apr 13 14:44 shims
-rw-r--r--   1 bakerj  OCLC\Domain Users    18 Apr  9 16:20 version
drwxr-xr-x   8 bakerj  OCLC\Domain Users   272 Apr  9 16:20 versions
bakerj1-mbpdu:.jenv bakerj$ pwd
/Users/bakerj/.jenv
bakerj1-mbpdu:.jenv bakerj$ echo $JAVA_HOME
/Users/bakerj/.jenv/fake-java-home
bakerj1-mbpdu:.jenv bakerj$ 
bakerj1-mbpdu:.jenv bakerj$ ls  $JAVA_HOME/bin
appletviewer	jar		javadoc		jcmd		jhat		jmc		jstack		keytool		policytool	schemagen	unpack200
apt		jarsigner	javafxpackager	jconsole	jinfo		jps		jstat		native2ascii	rmic		serialver	wsgen
extcheck	java		javah		jdb		jjs		jrunscript	jstatd		orbd		rmid		servertool	wsimport
idlj		javac		javap		jdeps		jmap		jsadebugd	jvisualvm	pack200		rmiregistry	tnameserv	xjc
bakerj1-mbpdu:.jenv bakerj$ 
</pre>

Groovy and Maven and Gradle all react as expected (meaning they react to any local .java-version files)

**Comment by mcandre** [comment]
+1 Same behavior on my machine, with multiple command line applications and with IntelliJ.

**Comment by Aiglobelam** [comment]
Hello there, have not read all comments about how to handle $JAVA_HOME... But I followed @solidjb example and it worked like a charm.

**Comment by fvm** [comment]
Although most things seem to work fine, there's one small part where the export plugin fails and that's on the level of Mac OS X system environment variables. This is a problem, because IntelliJ IDEA looks at those for the value of JAVA_HOME for Maven.
To fix this, one should add the value to the system environment using: `launchctl setenv JAVA_HOME "$(jenv javahome)"`. I've put this in my own `.zshrc`, but this should ideally be in a plugin (specifically for OS X).

**Comment by snimavat** [comment]
sdkman needs JAVA_HOME.. but jenv doesnt set it..

**Comment by gcuisinier** [comment]
You can set JAVA_HOME (and JDK_HOME) by enabling the export plugin

```jenv enable-plugin export```

**Comment by danielsotopino** [comment]
@gcuisinier that totally did the job

**Comment by mehrad-rafigh** [comment]
When i do `jenv enable-plugin export` I get 

> jenv: no such command `enable-plugin'

Gonna go delete jenv from my machine....

**Comment by danielsotopino** [comment]
what version of jenv do you have ?

**Comment by nardras** [comment]
same here - version is jenv 0.4.4

**Comment by berezovskyi** [comment]
Maven 3.5 was picking up 9-ea irrespective of the jenv config. `jenv enable-plugin export` solved the problem.

**Comment by HaoH** [comment]
add the following line in `.zsh` or `.bashrc`
`export JAVA_HOME="$(jenv prefix)`
after
`if which jenv > /dev/null; then eval "$(jenv init -)"; fi`

**Comment by AmmarHasan** [comment]
@HaoH  you forgot to put " at the end of the line
> `export JAVA_HOME="$(jenv prefix)`"

Thanks, it worked

**Comment by kyounger** [comment]
When running `jenv global x.y.z` (`local`, neither) it doesn't seem to automatically update JAVA_HOME in the current shell.

**Comment by MicahLC** [comment]
Since no one mentioned it, and it was blocking me, per #78, if you have ~/.mavenrc present and pointing to a JDK, it will ignore what you do with `jenv`, even if you have everything else set up properly. Nothing from this thread was working for me, and then I commented out the line in that file setting JAVA_HOME and now everything is working great 👍

**Comment by Skoti** [comment]
```
jenv doctor
[OK]	JAVA_HOME variable probably set by jenv PROMPT
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```
```
java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```
```
mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre
Default locale: en_PL, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"
```
So these above seem to work but when I run `sdkmanager` I get:
`Error: Could not find or load main class java.se.ee`
Which means it still uses java 11 which does not have ee modules.
Same error when I execute `jenv exec sdkmanager`, same when I execute `gradle` or `jenv exec gradle`. Even though gradle plugin (in jenv) is enabled.
And same when I run `./gradlew some_command` in Android Studio terminal.

My `jenv versions`:
```
  system
  1.8
  1.8.0.202-ea
  11.0
  11.0.2
  openjdk64-11.0.2
* oracle64-1.8.0.202-ea (set by /usr/local/var/jenv/version)
```

My path:
```
/Users/{redacted_user}/.rbenv/bin:/Users/{redacted_user}/.rbenv/shims:/usr/local/var/jenv/shims:/usr/local/sbin:/usr/local/opt/maven/bin:/usr/local/opt/gradle/bin:/usr/local/opt/ant/bin:/usr/local/share/android-sdk/tools:/usr/local/share/android-sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/{redacted_user}/.nodebrew/current/bin:/Users/{redacted_user}/.rbenv/bin:/Users/{redacted_user}/.rbenv/shims:/usr/local/var/jenv/shims:/usr/local/sbin:/usr/local/opt/maven/bin:/usr/local/opt/gradle/bin:/usr/local/opt/ant/bin:/usr/local/share/android-sdk/tools:/usr/local/share/android-sdk/platform-tools:/Users/{redacted_user}/.jenv/bin
```

Any thoughts?

**Comment by ati90ati** [comment]
To get maven to us the java version from jenv (maven uses JAVA_HOME):

`echo ‘JAVA_HOME=$(/usr/libexec/java_home -v $(jenv version-name))’ >> ~/.mavenrc`
`source ~/.mavenrc`

https://medium.com/@danielnenkov/multiple-jdk-versions-on-mac-os-x-with-jenv-5ea5522ddc9b

**Comment by astubbs** [comment]
Nearly nothing suggested here for fish worked for me, nor in the readme, or in the scripts output. I added this to my .config/fish/config.fish
```set -x JAVA_HOME (jenv prefix)```

**Comment by nicechester** [comment]
I had same issue with maven and JAVA_HOME after upgrading my jenv using homebrew and finally found the solution for me.
It seems like plugins need to be disabled and enabled to fix the issue.
```
jenv disable-plugin maven
jenv disable-plugin export
jenv enable-plugin maven
jenv enable-plugin export
```
I actually, opened up new terminal after disabling plugins and continued there.
Hopefully, it helps someone else having same issue with me.

**Comment by adrian-skybaker** [comment]
>Any reason the export plugin isn't enabled by default?

This would be much better. Especially since it seems quite tricky/error-prone to even get the plugin enabled, especially in a scripted/unattended fashion that doesn't rely on "restart your terminal to fix" (see https://github.com/jenv/jenv/issues/64).

**Comment by cglacet** [comment]
Thanks @gcuisinier for [this advice](https://github.com/jenv/jenv/issues/44#issuecomment-39359051), I had a [similar problem](https://github.com/react-native-async-storage/async-storage/issues/496#issuecomment-790487203) with a React Native app. Since React Native uses gradle, it seems the following solved the issue:

```bash
jenv enable-plugin gradle
```
