### ISSUE TITLE
jenv "~/.jenv/libexec/../completions/jenv.bash:15: command not found: complete"

### ISSUE THREAD

**Issue by autra** [gcuisinier/jenv#50]
On ubuntu 14.04 with zsh, fresh install, when I start zsh after having followed the install instructions.

Am I missing a dependency ? It is funny that it tries to use the bash completion though.

**Comment by BillHan** [comment]
the same issue.
* input .zshrc
![snip20150804_2](https://cloud.githubusercontent.com/assets/1904505/9060485/ffd3f4e8-3ae6-11e5-8181-0349c3b5de48.png)
* when first load terminal 
![snip20150804_3](https://cloud.githubusercontent.com/assets/1904505/9060527/4cc18f90-3ae7-11e5-84f9-011c0226f06f.png)

**Comment by baopham** [comment]
As @trollr said, set your `SHELL` in your `.zprofile`: `export SHELL=/usr/local/bin/zsh`. It works for me.

**Comment by shiruba** [comment]
@guidoilbaldo I bet you changed the shell in your Terminal.app. This executes a zsh shell in a bash environment and does not update your environment settings. The clean way in OS X would be to change your default login shell, which is described here: http://apple.stackexchange.com/a/88296

**Comment by guidoilbaldo** [comment]
@shiruba yep, you were right :)
changed my shell solved the problem! Thank you!

**Comment by Marthyn** [comment]
I fixed this by putting the following in my `.zshrc` file:
```
autoload bashcompinit
bashcompinit
```

**Comment by rockholla** [comment]
I believe there's a jenv problem around this, as my default shell is appropriately set to zsh and having this problem. You can see my default shell and then the output of `jenv init -` in that shell still trying to use bash:

```
******@******** .jenv % echo $SHELL
/bin/zsh
******@******** % jenv init -
export PATH="/Users/*******/.jenv/shims:${PATH}"
export JENV_SHELL=bash
export JENV_LOADED=1
unset JAVA_HOME
unset JDK_HOME
source '/Users/*******/.jenv/libexec/../completions/jenv.bash'
jenv rehash 2>/dev/null
jenv refresh-plugins
source "/Users/*******/.jenv/plugins/export/etc/jenv.d/init/export_jenv_hook.bash"
jenv() {
  typeset command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  enable-plugin|rehash|shell|shell-options)
    eval `jenv "sh-$command" "$@"`;;
  *)
    command jenv "$command" "$@";;
  esac
}
```
