### ISSUE TITLE
No such file or directory when adding a jdk on freshly installed jenv

### ISSUE THREAD

**Issue by cahi** [gcuisinier/jenv#76]
I installed JEnv via Homebrew. 
After installing, i tried to install a jdk 1.7 which I installed earlier:
console output:
cahi$: jenv add /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
cahi$: ln: /Users/cahi/.jenv/versions/oracle64-1.7.0.71: No such file or directory

**Comment by gcuisinier** [comment]
Do you have ```$(jenv init -)``` in your .zshrc or .bash_profile ?

**Comment by cahi** [comment]
Thanks for the hint. You need to restart a new console after adding configuring the jenv ;-)

**Comment by evanleonard** [comment]
Just ran into this myself. Would you consider either a) updating the error message that comes out at this point to suggest the fix? or updating the docs on http://www.jenv.be/ to say "start a new console" in the "installation" section.
