### ISSUE TITLE
I had to mkdir some directories after a homebrew intall.

### ISSUE THREAD

**Issue by paul-hammant** [gcuisinier/jenv#77]
$  brew install jenv
==> Downloading https://github.com/gcuisinier/jenv/archive/0.4.2.tar.gz
######################################################################## 100.0%
==> Patching
==> Caveats
To enable shims and autocompletion add to your profile:
  if which jenv > /dev/null; then eval "$(jenv init -)"; fi

To use Homebrew's directories rather than ~/.jenv add to your profile:
  export JENV_ROOT=/usr/local/opt/jenv
==> Summary
🍺  /usr/local/Cellar/jenv/0.4.2: 74 files, 308K, built in 2 seconds
$ jenv add /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
ln: /Users/paul/.jenv/versions/oracle64-1.6.0.65: No such file or directory

# The fix (for me):

mkdir -p /Users/paul/.jenv/versions

**Comment by TerrenceChen** [comment]
Hi Paul, 

I encountered exactly same issue as yours. But after try your solution, my issue exist. What shall I do to find the bug? Could you please give me some suggestions?

Thank you

**Comment by TerrenceChen** [comment]
Hi ! I tried restarting my terminal. However, I managed to add the jdk!
But I still do not understand what had happened. Do you know why it is like that?

Thanks!

**Comment by Toilal** [comment]
Same issue here, using docker based on ubuntu:14.04 (so a fresh and minimalist install).

`.jenv/versions` must be manually created before calling `jenv add`.

**Comment by gcuisinier** [comment]
You have to enable jenv in your bash_profile or zshrc. 

Bash

$ echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile $ echo 'eval "$(jenv init -)"' >> ~/.bash_profile 

Zsh

$ echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc $ echo 'eval "$(jenv init -)"' >> ~/.zshrc

**Comment by Toilal** [comment]
:+1: Thanks. I'm using jenv in a non interactive shell, so i though this jenv init thing was not usefull (and that's the case for others environment managers, like rbenv or pyenv). 

Maybe README text could be adjusted ("Add jenv init to your shell to enable shims and autocompletion.") as it's more that only this.

**Comment by gcuisinier** [comment]
Indeed, I'll fix the comment :)

**Comment by bytor99999** [comment]
Same issue with me. The .jenv directory never gets created when brew install jenv, or when running
 
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc $ echo 'eval "$(jenv init -)"' >> ~/.zshrc

There should at least be something in the docs stating that you have to manually create that .jenv directory in your home directory.

**Comment by gcuisinier** [comment]
Hi,

It should be a bug. I am using brew install too, zsh under OSX, and I don't need to create .jenv folder manually.
I will investigate about this.

**Comment by gcuisinier** [comment]
Just to be sure, what do you do ?

- brew install jenv
- echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc $ echo 'eval "$(jenv init -)"' >> ~/.zshrc

But do you restart your shell after or not ?
jenv init will be execute on "next" shell initialisation .. and will create the missing directory.

I need to mention that on doc.

**Comment by bytor99999** [comment]
At that time I did not restart my shell as I had a Cassandra running in one tab, RabbitMQ in another, and if I shut down Cassandra, I actually have to reboot my machine in order to get it to start up again.

But, I agree I think it should be put in the docs that you HAVE to restart the shell after installation. I also spent a good 20-30 minutes wondering why jenv global 1.8 and jenv global 1.7 wasn’t changing my java or javac versions, and that both were pointing to completely different JVM versions. ;)

Everything is working perfectly now. jenv is fantastic and I really appreciate you all writing it.

Mark

**Comment by samhandev** [comment]
I've just installed jenv using homebrew and then installed java with `brew cask install java`.

running `jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/` also caused 
`ln: /Users/shan/.jenv/versions/oracle64-1.8.0.66: No such file or directory`

After I created `~/.jenv/versions` I was able to add the jdk with the previous command.

OS X 10.10.5

**Comment by gcuisinier** [comment]
Do you have ```eval "$(jenv init -)"``` in you zsh/bash init ?
this command prepare the directory etc ..

**Comment by samhandev** [comment]
I've just removed the versions and then added that to my .zshrc file.

It works fine now, Thanks!

**Comment by jknipp** [comment]
Adding `eval "$(jenv init -)"` to my .zshrc file worked for me - thanks!
