### ISSUE TITLE
jenv: no such command `install' ,how do I install jdk 1.7 or 1.6 by jenv

### ISSUE THREAD

**Issue by ArvoGuo** [gcuisinier/jenv#81]
➜  ~  jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded

➜  ~  jenv install
jenv: no such command `install'

➜  ~  jenv commands 
--version
add
commands
completions
disable-plugin
doctor
enable-plugin
exec
global
global-options
help
hooks
info
init
javahome
local
local-options
options
options-file
options-file-read
options-file-write
options-origin
plugins
prefix
refresh-versions
rehash
remove
root
shell
shell-options
shims
version
version-file
version-file-read
version-file-write
version-name
version-origin
versions
whence
which

~/.zshrc
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

**Comment by ArvoGuo** [comment]
I install jenv  by  : brew install jenv 
this is version:

➜  ~  jenv --version
jenv 0.4.0

**Comment by gcuisinier** [comment]
There is no way to install JDK with jenv,  you have to do it manually. 

After you can use it with jenv add

**Comment by ArvoGuo** [comment]
oh , I thought it has method of install . I'm wrong.
thx.
