### ISSUE TITLE
jenv.bash - No such file or directory

### ISSUE THREAD

**Issue by MehmetNUK** [gcuisinier/jenv#86]
I'm getting this error message whenever i fire up a terminal on Mac OS X mavericks:

`-bash: /usr/local/Cellar/jenv/0.2.0-201404260/libexec/../completions/jenv.bash: No such file or directory`

There is a line as the following when I run "jenv init -":
`source "/usr/local/Cellar/jenv/0.2.0-201404260/libexec/../completions/jenv.bash"`

there is no "`jenv.bash`" file under the whole jenv directory structure.

thanks for the help.

**Comment by slangeberg** [comment]
I was following jenv setup at http://hanxue-it.blogspot.com/2014/05/installing-java-8-managing-multiple.html

He said to activate jenv with: 

> $ echo 'eval "$(jenv init -)"' >> ~/.bash_profile

And I'm getting same error message
>-bash: /usr/local/Cellar/jenv/0.2.0-201404260/libexec/../completions/jenv.bash: No such file or directory

**Comment by slangeberg** [comment]
Here's what i ran:

> echo $(jenv init -)

Which produced:

> export PATH="/Users/scott/.jenv/shims:${PATH}" source "/usr/local/Cellar/jenv/0.2.0-201404260/libexec/../completions/jenv.bash" jenv rehash 2>/dev/null export JENV_LOADED=1 unset JAVA_HOME jenv() { typeset command command="$1" if [ "$#" -gt 0 ]; then shift fi case "$command" in enable-plugin|rehash|shell|shell-options) eval `jenv "sh-$command" "$@"`;; *) command jenv "$command" "$@";; esac }

Please let me know if that profile config looks good. Guess I'll try it out :)

**Comment by slangeberg** [comment]
Ah, there really is no file present:

> $ cat: /usr/local/Cellar/jenv/0.2.0-201404260/libexec/../completions/jenv.bash: No such file or directory

Not sure if this is because of Homebrew install?

**Comment by MehmetNUK** [comment]
I've fixed the problem by manually creating the file. Probably the issue is arising because of the homebrew somehow.
created `completions` folder under `cd /usr/local/Cellar/jenv/0.2.0-201404260/`
`mkdir completions`
`cd completions`
created `jenv.bash` file under completions. and edited the content with an editor, you can find the script here: https://github.com/gcuisinier/jenv/blob/master/completions/jenv.bash, and saved it.

**Comment by EvilJohn** [comment]
I'm seeing this same thing with zsh and homebrew install, too.

**Comment by bradparks** [comment]
hey... how do you use that formula? I'm not up on my homebrew... thanks!

**Comment by MehmetNUK** [comment]
`$ brew install https://raw.githubusercontent.com/jenv/homebrew-jenv/master/jenv.rb`

**Comment by richardwlu** [comment]
Came across this issue. I had just installed using `brew install https://raw.githubusercontent.com/jenv/homebrew-jenv/master/jenv.rb` but I still had to manually add `jenv.bash`

**Comment by hgontijo** [comment]
I hit the same issue. That's how I solved it:

# remove https://raw.githubusercontent.com/jenv/homebrew-jenv/master/jenv.rb
$ brew remove jenv
# install https://github.com/gcuisinier/jenv
$ brew install jenv

**Comment by devlifealways** [comment]
Same problem, it seems to me that the folder completions is not created ! neither it's inner file jenv.bash
