### ISSUE TITLE
can't reset  JAVA_HOME from 1.7 to 1.8

### ISSUE THREAD

**Issue by droid-Q** [gcuisinier/jenv#90]
When i run 'jenv shell 1.8' ,the java version is 1.8,but i found JAVA_HOME still is 1.7.I had set .zshrc like this "export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`" "
![2015-04-01 9 14 25](https://cloud.githubusercontent.com/assets/708277/6932676/89c9981a-d84f-11e4-84da-c64cc0098b04.png)

How can i fix it?

**Comment by fpavageau** [comment]
Have you enabled the `export` plugin?

    jenv enable-plugin export

It works for me:

    fpavageau@fpmac:~$ jenv version
    1.8 (set by /Users/fpavageau/.jenv/version)
    fpavageau@fpmac:~$ echo $JAVA_HOME
    /Users/fpavageau/.jenv/versions/1.8
    fpavageau@fpmac:~$ jenv shell 1.7
    fpavageau@fpmac:~$ echo $JAVA_HOME
    /Users/fpavageau/.jenv/versions/1.7

**Comment by droid-Q** [comment]
it's not work for me.
![2015-04-02 4 24 44](https://cloud.githubusercontent.com/assets/708277/6960438/ec0afe32-d954-11e4-9013-25e9d15bd1a7.png)

**Comment by fpavageau** [comment]
I'm using bash, so I guess the issue might be the zsh integration (since you mentioned `.zshrc`).

I'm not setting anything JDK-related in `.bashrc` besides `jenv`:
```
PATH=$HOME/.jenv/bin:$M2_HOME/bin:${PATH}
eval "$(jenv init -)"
export PATH
```

Have you tried `jenv doctor`?
```
fpavageau@fpmac:~$ jenv doctor
[OK]	JAVA_HOME variable probably set by jenv PROMPT
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```

**Comment by droid-Q** [comment]
Yes,i had enable the "export" plugin.
```
    ┌─[droid@droid-rMBP] - [~/.jenv/versions] - [2015-04-02 06:16:10]
    └─[0] jenv enable-plugin export
    export plugin already enabled`
```

and I already had removed :
```"export JAVA_HOME="$HOME/.jenv/versions/jenv version-name" ```

It's still not work.
```
┌─[droid@droid-rMBP] - [~] - [2015-04-02 06:26:48]
└─[0] jenv version
1.7 (set by /Users/droid/.jenv/version)
┌─[droid@droid-rMBP] - [~] - [2015-04-02 06:26:51]
└─[0] jenv shell 1.8
┌─[droid@droid-rMBP] - [~] - [2015-04-02 06:27:17]
└─[0] echo $JAVA_HOME
/Users/droid/.jenv/versions/1.7
```

**Comment by gcuisinier** [comment]
Strange.

Could you provide output : 

```
echo $chpwd_functions
```

Thanks

**Comment by droid-Q** [comment]
it is :
```
─[droid@droid-rMBP] - [~] - [2015-04-02 07:49:31]
└─[0] echo $chpwd_functions
_jenv_export_hook __rvm_cd_functions_set
```

**Comment by gcuisinier** [comment]
That's very strange ... the hook seems well registered.

**Comment by droid-Q** [comment]
```
└─[0] echo $JENV_FORCEJAVAHOME
true
```

**Comment by fpavageau** [comment]
It seems unlikely, but a conflict with RVM which is also registered?

You can debug what happens by using `set -x`, though:
```
fpavageau@fpmac:~$ set -x
++ _jenv_export_hook
+++ jenv javahome
+++ typeset command
+++ command=javahome
+++ '[' 1 -gt 0 ']'
+++ shift
+++ case "$command" in
+++ command jenv javahome
+++ jenv javahome
++ export JAVA_HOME=/Users/fpavageau/.jenv/versions/1.8
++ JAVA_HOME=/Users/fpavageau/.jenv/versions/1.8
++ export JENV_FORCEJAVAHOME=true
++ JENV_FORCEJAVAHOME=true
++ update_terminal_cwd
++ local 'SEARCH= '
++ local REPLACE=%20
++ local PWD_URL=file://fpmac.local/Users/fpavageau
++ printf '\e]7;%s\a' file://fpmac.local/Users/fpavageau
++ __git_ps1 ' (%s)'
++ local pcmode=no
++ local detached=no
++ local 'ps1pc_start=\u@\h:\w '
++ local 'ps1pc_end=\$ '
++ local 'printf_format= (%s)'
++ case "$#" in
++ printf_format=' (%s)'
++ local ps1_expanded=yes
++ '[' -z '' ']'
++ '[' -z '3.2.57(1)-release' ']'
++ shopt -q promptvars
++ local repo_info rev_parse_exit_code
+++ git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree --short HEAD
++ repo_info=
++ rev_parse_exit_code=128
++ '[' -z '' ']'
++ '[' no = yes ']'
++ return
fpavageau@fpmac:~$
```
(mixed with my git prompt management)

You can see it does set `JAVA_HOME` (twice actually, once when exporting, once without, which seems unnecessary).

**Comment by droid-Q** [comment]
this is very strange:
```
─[0] echo $JAVA_HOME
/Users/droid/.jenv/versions/1.7
┌─[droid@droid-rMBP] - [~] - [2015-04-02 10:41:03]
└─[0] cd .jenv
┌─[droid@droid-rMBP] - [~/.jenv] - [2015-04-02 10:41:10]
└─[0] echo $JAVA_HOME
/Users/droid/.jenv/versions/1.8
┌─[droid@droid-rMBP] - [~/.jenv] - [2015-04-02 10:41:13]
└─[0] cd ..
┌─[droid@droid-rMBP] - [~] - [2015-04-02 10:42:43]
└─[0] echo $JAVA_HOME
/Users/droid/.jenv/versions/1.8
```
when i run echo $JAVA_HOME in the "~/.jenv/",The result is right.

**Comment by gcuisinier** [comment]
Do you find a solution ?

**Comment by droid-Q** [comment]
No,now i just write an alias in the ".zshrc",and set java version to 1.8 and source .zshrc.
