### ISSUE TITLE
Please update version to 0.4.3

### ISSUE THREAD

**Issue by bosr** [gcuisinier/jenv#97]
Hi, thanks for your work on `jenv`, it is really helpful.

For the `jenv` Homebrew formula to be updated and include the latest corrections on some plugins, could you please bump a new version? The current formula points to the latest release: 0.4.2 (oct 2014). I can take care of updating the formula.

Thanks in advance,
et je boirai une Rochefort à ta santé :)

Romain

**Comment by gcuisinier** [comment]
Tag is done. Do you want to update the formula? :)

**Comment by bosr** [comment]
Gildas, please check #99

**Comment by gcuisinier** [comment]
Done ! Thanks

**Comment by bosr** [comment]
Et une rochefort, une !

**Comment by bosr** [comment]
@gcuisinier, for your information, homebrew has merged `0.4.3`: https://github.com/Homebrew/homebrew/pull/40473
