### ISSUE TITLE
/Library/Java/JavaVirtualMachines/jdk17011.jdk/Contents/Home is not a valid path to java installation

### ISSUE THREAD

**Issue by ckitterl** [gcuisinier/jenv#98]
run 

    jenv add /Library/Java/JavaVirtualMachines/jdk17011.jdk/Contents/Home oracle64-1.7.0.11 added

command on bash, and get the error below:

    /Library/Java/JavaVirtualMachines/jdk17011.jdk/Contents/Home is not a valid path to java installation

**Comment by Unbr8kbal** [comment]
Try this
jenv add /Library/Java/JavaVirtualMachines/jdk1.7.0_11.jdk/Contents/Home
